services:
  postgres:
    image: postgres:16-alpine
    container_name: tickethub-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tickethub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 321
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: tickethub-query-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 321
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tickethub-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 321

volumes:
  postgres_data:
  mongo_data: